ln -s dela.py dela
ln -s deli.py deli
ln -s delo.py delo
ln -s delp.py delp
ln -s lsa.py lsa
ln -s lsi.py lsi
ln -s lso.py lso
ln -s lsp.py lsp
ln -s morsel.py morsel
ln -s qjob.py qjob
ln -s qping.py qping
ln -s qrm.py qrm
ln -s showo.py showo
